export * from './auth.service';
import { AuthService } from './auth.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './task.service';
import { TaskService } from './task.service';
export * from './team.service';
import { TeamService } from './team.service';
export * from './team-settings.service';
import { TeamSettingsService } from './team-settings.service';
export * from './time-off.service';
import { TimeOffService } from './time-off.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuthService, ProjectService, TaskService, TeamService, TeamSettingsService, TimeOffService, UserService];
