/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserBase } from './user-base';


export interface TimeOff { 
    id: string;
    user: UserBase;
    startDate: string;
    endDate: string;
    duration: number;
    reason?: string;
}

