/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamBase } from './team-base';
import { TimeOffBase } from './time-off-base';
import { TaskBase } from './task-base';


export interface UserBase { 
    id: string;
    username: string;
    password: string;
    teams: Array<TeamBase>;
    adminIn: Array<TeamBase>;
    tasks: Array<TaskBase>;
    timeOffs: Array<TimeOffBase>;
}

